ARG  NOTEBOOK_VERSION
FROM ghcr.io/comp-dev-cms-ita/jupyterlab:${NOTEBOOK_VERSION}-base
USER root

# Dask and jupyterhub
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --upgrade setuptools
RUN python3 -m pip install dask \
    dask_jobqueue \
    click==7.1.2 \
    numpy \
    bokeh \
    ipython \
    jupyterhub \
    jupyterlab \
    notebook \
    jupyter-server-proxy \
    ipywidgets
RUN python3 -m pip install "dask[dataframe]"

# Install DASK jobqueue
#RUN pip install dask-remote-jobqueue==0.4.21


RUN npm install npm@latest -g
RUN npm install -g typescript yarn


# Install DASK labextension
WORKDIR /usr/local/share/comp-dev-cms-ita
RUN git clone --branch af_plugin https://github.com/comp-dev-cms-ita/dask-labextension.git

WORKDIR /usr/local/share/comp-dev-cms-ita/dask-labextension
COPY labextension.yaml /usr/local/share/comp-dev-cms-ita/dask-labextension/dask_labextension/
COPY labextension.yaml /usr/local/share/comp-dev-cms-ita/dask-labextension/
RUN jlpm
RUN jlpm build && pip install .

WORKDIR /usr/local/share/comp-dev-cms-ita

RUN git clone --branch submit_as_user https://github.com/comp-dev-cms-ita/dask-remote-jobqueue
# WORKDIR /usr/local/share/comp-dev-cms-ita/dask-remote-jobqueue
# RUN python3 setup.py install
# WORKDIR /usr/local/share/comp-dev-cms-ita
RUN cd /usr/local/share/comp-dev-cms-ita/dask-remote-jobqueue && python3 setup.py install


RUN mkdir -p /root/.ipython

COPY ./jupyterhub-singleuser.sh /usr/local/bin/jupyterhub-singleuser.sh
COPY kernel.json /opt/conda/share/jupyter/kernels/python3/kernel.json
RUN chmod +x /usr/local/bin/jupyterhub-singleuser.sh
WORKDIR /opt/workspace
